//
// This file is part of the game "The Legend of Zelda: Ocarina of Time".
// Copyright (C) 1998-2003  The Legend of Zelda: Ocarina of Time Team
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//

#include "history.h"

History::History()
{
    m_history.clear();
    m_history.reserve(100);
}

History::~History()
{
}

void History::add(const std::string& s)
{
    m_history.push_back(s);
}

void History::add(const std::string& s, const std::string& t)
{
    m_history.push_back(s);
    m_history.push_back(t);
}

void History::add(const std::string& s, const std::string& t, const std::string& u)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m, const std::string& n, const std::string& o, const std::string& p, const std::string& q, const std::string& r, const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string& z, const std::string& a, const std::string& b, const std::string& c, const std::string& d, const std::string& e, const std::string& f, const std::string& g, const std::string& h, const std::string& i, const std::string& j, const std::string& k, const std::string& l, const std::string& m)
{
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
    m_history.push_back(n);
    m_history.push_back(o);
    m_history.push_back(p);
    m_history.push_back(q);
    m_history.push_back(r);
    m_history.push_back(s);
    m_history.push_back(t);
    m_history.push_back(u);
    m_history.push_back(v);
    m_history.push_back(w);
    m_history.push_back(x);
    m_history.push_back(y);
    m_history.push_back(z);
    m_history.push_back(a);
    m_history.push_back(b);
    m_history.push_back(c);
    m_history.push_back(d);
    m_history.push_back(e);
    m_history.push_back(f);
    m_history.push_back(g);
    m_history.push_back(h);
    m_history.push_back(i);
    m_history.push_back(j);
    m_history.push_back(k);
    m_history.push_back(l);
    m_history.push_back(m);
}

void History::add(const std::string& s, const std::string& t, const std::string& u, const std::string& v, const std::string& w, const std::string& x, const std::string& y, const std::string