import os

try:
    Import("env")
except NameError:
    print("Erreur : Ce script doit être exécuté via PlatformIO (pio run).")
    exit(1)

def to_c_array(binary_data):
    """Convert binary data to a C char array string."""
    return ", ".join(f"0x{byte:02x}" for byte in binary_data)

def embed_web_files(source, target, env):
    """
    Scans the 'data' directory and embeds each file into a C++ header
    as a PROGMEM char array.
    """
    web_pages_h_path = os.path.join(env.get("PROJECT_INCLUDE_DIR"), "web_pages.h")
    data_dir = os.path.join(env.get("PROJECT_DIR"), "data")

    print("--- Embedding web files ---")
    
    try:
        with open(web_pages_h_path, "w") as h_file:
            h_file.write("#pragma once\n\n")
            h_file.write("/*\n")
            h_file.write(" * This file is automatically generated by 'embed_web_files.py'.\n")
            h_file.write(" * Do not edit this file manually.\n")
            h_file.write(" */\n\n")
            h_file.write("#include <pgmspace.h>\n\n")

            if not os.path.exists(data_dir):
                 print(f"Warning: {data_dir} does not exist. Skipping embedding.")
                 return

            for item in sorted(os.listdir(data_dir)):
                file_path = os.path.join(data_dir, item)
                if os.path.isfile(file_path):
                    variable_name = "web_" + item.replace('.', '_').replace('-', '_')
                    print(f"Embedding '{item}' as '{variable_name}'")

                    with open(file_path, "rb") as f:
                        content = f.read()
                        
                    h_file.write(f"// Content of file: {item}\n")
                    h_file.write(f"const char {variable_name}[] PROGMEM = {{\n    ")
                    
                    # Write data in chunks to keep lines readable
                    for i in range(0, len(content), 16):
                        chunk = content[i:i+16]
                        h_file.write(to_c_array(chunk) + ",\n    ")
                    
                    h_file.write("0x00\n};\n\n") # Null terminator

        print(f"Successfully generated '{web_pages_h_path}'")

    except Exception as e:
        print(f"Error generating web_pages.h: {e}")

# Register the builder
embed_web_files(None, None, env)